from __future__ import annotations

BACKUP_DIR: str = '/backups'

COLOR_KEYS: list[str] = [
    'color_navbar', 'color_bg', 'color_text', 'color_accent',
    'color_card_bg', 'color_footer_bg', 'color_link', 'color_muted',
    'color_border', 'color_card_header_bg', 'color_input_bg',
]

EFFECT_KEYS: list[str] = [
    'typing_speed', 'particle_count',
]

ALL_THEME_KEYS: list[str] = COLOR_KEYS + EFFECT_KEYS

THEMES: dict[str, dict[str, str]] = {
    # --- Static themes ---
    'klassisch': {
        'label': 'Klassisch',
        'color_navbar': '#6b4c3b',
        'color_bg': '#faf6f0',
        'color_text': '#3e2c1c',
        'color_accent': '#c9a96e',
        'color_card_bg': '#ffffff',
        'color_footer_bg': '#f0ebe3',
        'color_link': '#8b6914',
        'color_muted': '#8a7a6a',
        'color_border': '#e0d6c8',
        'color_card_header_bg': '#f5ede0',
        'color_input_bg': '#ffffff',
        'body_class': '',
        'preview_css': '',
        'typing_speed': '0',
        'particle_count': '0',
    },
    'modern': {
        'label': 'Modern',
        'color_navbar': '#2563eb',
        'color_bg': '#ffffff',
        'color_text': '#1e293b',
        'color_accent': '#3b82f6',
        'color_card_bg': '#f8fafc',
        'color_footer_bg': '#f1f5f9',
        'color_link': '#2563eb',
        'color_muted': '#64748b',
        'color_border': '#e2e8f0',
        'color_card_header_bg': '#f1f5f9',
        'color_input_bg': '#ffffff',
        'body_class': '',
        'preview_css': '',
        'typing_speed': '0',
        'particle_count': '0',
    },
    'dunkel': {
        'label': 'Dunkel',
        'color_navbar': '#1e1e2e',
        'color_bg': '#181825',
        'color_text': '#cdd6f4',
        'color_accent': '#89b4fa',
        'color_card_bg': '#313244',
        'color_footer_bg': '#11111b',
        'color_link': '#89b4fa',
        'color_muted': '#888899',
        'color_border': '#444466',
        'color_card_header_bg': '#3a3a4a',
        'color_input_bg': '#313244',
        'body_class': '',
        'preview_css': '',
        'typing_speed': '0',
        'particle_count': '0',
    },
    'wald': {
        'label': 'Wald',
        'color_navbar': '#2d6a4f',
        'color_bg': '#f0f7f4',
        'color_text': '#1b4332',
        'color_accent': '#52b788',
        'color_card_bg': '#ffffff',
        'color_footer_bg': '#d8f3dc',
        'color_link': '#40916c',
        'color_muted': '#5a8a6a',
        'color_border': '#c8e6d0',
        'color_card_header_bg': '#e8f5ec',
        'color_input_bg': '#ffffff',
        'body_class': '',
        'preview_css': '',
        'typing_speed': '0',
        'particle_count': '0',
    },
    'ozean': {
        'label': 'Ozean',
        'color_navbar': '#0077b6',
        'color_bg': '#f0f8ff',
        'color_text': '#023e58',
        'color_accent': '#00b4d8',
        'color_card_bg': '#ffffff',
        'color_footer_bg': '#caf0f8',
        'color_link': '#0096c7',
        'color_muted': '#4a7a8a',
        'color_border': '#b8e0f0',
        'color_card_header_bg': '#e0f4ff',
        'color_input_bg': '#ffffff',
        'body_class': '',
        'preview_css': '',
        'typing_speed': '0',
        'particle_count': '0',
    },

    # --- Animated themes ---
    'hacker': {
        'label': 'Hacker Terminal',
        'color_navbar': '#0a0a0a',
        'color_bg': '#0d0d0d',
        'color_text': '#00ff41',
        'color_accent': '#00ff41',
        'color_card_bg': '#0a0f0a',
        'color_footer_bg': '#050505',
        'color_link': '#00ff41',
        'color_muted': '#00dd44',
        'color_border': '#003300',
        'color_card_header_bg': '#0a0f0a',
        'color_input_bg': '#0a0f0a',
        'body_class': 'theme-hacker',
        'preview_css': 'background:linear-gradient(180deg,#0a0a0a 0%,#001a00 100%)',
        'typing_speed': '18',
        'particle_count': '0',
    },
    'typewriter': {
        'label': 'Schreibmaschine',
        'color_navbar': '#3c3028',
        'color_bg': '#f5f0e1',
        'color_text': '#2c2416',
        'color_accent': '#8b4513',
        'color_card_bg': '#faf5e8',
        'color_footer_bg': '#ede6d3',
        'color_link': '#8b4513',
        'color_muted': '#6a5a4a',
        'color_border': '#d4c9b4',
        'color_card_header_bg': '#f0e8d8',
        'color_input_bg': '#faf5e8',
        'body_class': 'theme-typewriter',
        'preview_css': 'background:#f5f0e1',
        'typing_speed': '45',
        'particle_count': '0',
    },
    'neon': {
        'label': 'Neon Glow',
        'color_navbar': '#0a001a',
        'color_bg': '#0a001a',
        'color_text': '#e0d0ff',
        'color_accent': '#ff00ff',
        'color_card_bg': '#120025',
        'color_footer_bg': '#05000d',
        'color_link': '#00ffff',
        'color_muted': '#c0a0e0',
        'color_border': '#330033',
        'color_card_header_bg': '#150030',
        'color_input_bg': '#120025',
        'body_class': 'theme-neon',
        'preview_css': 'background:linear-gradient(135deg,#0a001a,#1a0033)',
        'typing_speed': '22',
        'particle_count': '0',
    },
    'pergament': {
        'label': 'Pergament',
        'color_navbar': '#5c3d2e',
        'color_bg': '#f0e4c8',
        'color_text': '#3b2a1a',
        'color_accent': '#8b5e3c',
        'color_card_bg': '#f5edd4',
        'color_footer_bg': '#e0d4b4',
        'color_link': '#8b5e3c',
        'color_muted': '#6a5040',
        'color_border': '#c4a97d',
        'color_card_header_bg': '#ede4cc',
        'color_input_bg': '#f5edd4',
        'body_class': 'theme-pergament',
        'preview_css': 'background:#f0e4c8',
        'typing_speed': '25',
        'particle_count': '0',
    },
    'vaporwave': {
        'label': 'Vaporwave',
        'color_navbar': '#1a0033',
        'color_bg': '#1a0a2e',
        'color_text': '#ff71ce',
        'color_accent': '#01cdfe',
        'color_card_bg': '#1e0e38',
        'color_footer_bg': '#110822',
        'color_link': '#01cdfe',
        'color_muted': '#c080d0',
        'color_border': '#2a1050',
        'color_card_header_bg': '#200e40',
        'color_input_bg': '#1e0e38',
        'body_class': 'theme-vaporwave',
        'preview_css': 'background:linear-gradient(135deg,#1a0033,#330066)',
        'typing_speed': '20',
        'particle_count': '0',
    },
    'aurora': {
        'label': 'Nordlichter',
        'color_navbar': '#0b132b',
        'color_bg': '#0b132b',
        'color_text': '#c8e6f0',
        'color_accent': '#5ce0d8',
        'color_card_bg': '#111d3a',
        'color_footer_bg': '#080e20',
        'color_link': '#5ce0d8',
        'color_muted': '#90c0d0',
        'color_border': '#1a3040',
        'color_card_header_bg': '#0f1932',
        'color_input_bg': '#0b132b',
        'body_class': 'theme-aurora',
        'preview_css': 'background:linear-gradient(135deg,#0b132b,#1c2951)',
        'typing_speed': '25',
        'particle_count': '0',
    },
    'unterwasser': {
        'label': 'Unterwasser',
        'color_navbar': '#003049',
        'color_bg': '#001828',
        'color_text': '#b0e0f0',
        'color_accent': '#00b4d8',
        'color_card_bg': '#002040',
        'color_footer_bg': '#001018',
        'color_link': '#00b4d8',
        'color_muted': '#80b8d0',
        'color_border': '#003050',
        'color_card_header_bg': '#002446',
        'color_input_bg': '#002040',
        'body_class': 'theme-unterwasser',
        'preview_css': 'background:linear-gradient(180deg,#003049,#001828)',
        'typing_speed': '30',
        'particle_count': '15',
    },
    'kosmos': {
        'label': 'Kosmos',
        'color_navbar': '#0a0015',
        'color_bg': '#060010',
        'color_text': '#d0c0f0',
        'color_accent': '#b088f9',
        'color_card_bg': '#0e0020',
        'color_footer_bg': '#040008',
        'color_link': '#b088f9',
        'color_muted': '#a098c8',
        'color_border': '#1a0030',
        'color_card_header_bg': '#0c001c',
        'color_input_bg': '#0e0020',
        'body_class': 'theme-kosmos',
        'preview_css': 'background:linear-gradient(180deg,#0a0015,#060010)',
        'typing_speed': '22',
        'particle_count': '80',
    },
    'feuer': {
        'label': 'Feuer',
        'color_navbar': '#1a0800',
        'color_bg': '#140600',
        'color_text': '#ffd6a5',
        'color_accent': '#ff6b35',
        'color_card_bg': '#1e0a00',
        'color_footer_bg': '#0a0300',
        'color_link': '#ff8c00',
        'color_muted': '#c0a880',
        'color_border': '#301000',
        'color_card_header_bg': '#230c00',
        'color_input_bg': '#1e0a00',
        'body_class': 'theme-feuer',
        'preview_css': 'background:linear-gradient(180deg,#1a0800,#0a0300)',
        'typing_speed': '20',
        'particle_count': '20',
    },
}

DEFAULT_THEME: str = 'klassisch'

QUOTES_PER_PAGE: int = 20
ADMIN_QUOTES_PER_PAGE: int = 50
