from __future__ import annotations

BACKUP_DIR: str = '/backups'

THEMES: dict[str, dict[str, str]] = {
    # --- Static themes ---
    'klassisch': {
        'label': 'Klassisch',
        'color_navbar': '#6b4c3b',
        'color_bg': '#faf6f0',
        'color_text': '#3e2c1c',
        'color_accent': '#c9a96e',
        'color_card_bg': '#ffffff',
        'color_footer_bg': '#f0ebe3',
        'body_class': '',
        'preview_css': '',
    },
    'modern': {
        'label': 'Modern',
        'color_navbar': '#2563eb',
        'color_bg': '#ffffff',
        'color_text': '#1e293b',
        'color_accent': '#3b82f6',
        'color_card_bg': '#f8fafc',
        'color_footer_bg': '#f1f5f9',
        'body_class': '',
        'preview_css': '',
    },
    'dunkel': {
        'label': 'Dunkel',
        'color_navbar': '#1e1e2e',
        'color_bg': '#181825',
        'color_text': '#cdd6f4',
        'color_accent': '#89b4fa',
        'color_card_bg': '#313244',
        'color_footer_bg': '#11111b',
        'body_class': '',
        'preview_css': '',
    },
    'wald': {
        'label': 'Wald',
        'color_navbar': '#2d6a4f',
        'color_bg': '#f0f7f4',
        'color_text': '#1b4332',
        'color_accent': '#52b788',
        'color_card_bg': '#ffffff',
        'color_footer_bg': '#d8f3dc',
        'body_class': '',
        'preview_css': '',
    },
    'ozean': {
        'label': 'Ozean',
        'color_navbar': '#0077b6',
        'color_bg': '#f0f8ff',
        'color_text': '#023e58',
        'color_accent': '#00b4d8',
        'color_card_bg': '#ffffff',
        'color_footer_bg': '#caf0f8',
        'body_class': '',
        'preview_css': '',
    },

    # --- Animated themes ---
    'hacker': {
        'label': 'Hacker Terminal',
        'color_navbar': '#0a0a0a',
        'color_bg': '#0d0d0d',
        'color_text': '#00ff41',
        'color_accent': '#00ff41',
        'color_card_bg': '#0a0f0a',
        'color_footer_bg': '#050505',
        'body_class': 'theme-hacker',
        'preview_css': 'background:linear-gradient(180deg,#0a0a0a 0%,#001a00 100%)',
    },
    'typewriter': {
        'label': 'Schreibmaschine',
        'color_navbar': '#3c3028',
        'color_bg': '#f5f0e1',
        'color_text': '#2c2416',
        'color_accent': '#8b4513',
        'color_card_bg': '#faf5e8',
        'color_footer_bg': '#ede6d3',
        'body_class': 'theme-typewriter',
        'preview_css': 'background:#f5f0e1',
    },
    'neon': {
        'label': 'Neon Glow',
        'color_navbar': '#0a001a',
        'color_bg': '#0a001a',
        'color_text': '#e0d0ff',
        'color_accent': '#ff00ff',
        'color_card_bg': '#120025',
        'color_footer_bg': '#05000d',
        'body_class': 'theme-neon',
        'preview_css': 'background:linear-gradient(135deg,#0a001a,#1a0033)',
    },
    'pergament': {
        'label': 'Pergament',
        'color_navbar': '#5c3d2e',
        'color_bg': '#f0e4c8',
        'color_text': '#3b2a1a',
        'color_accent': '#8b5e3c',
        'color_card_bg': '#f5edd4',
        'color_footer_bg': '#e0d4b4',
        'body_class': 'theme-pergament',
        'preview_css': 'background:#f0e4c8',
    },
    'vaporwave': {
        'label': 'Vaporwave',
        'color_navbar': '#1a0033',
        'color_bg': '#1a0a2e',
        'color_text': '#ff71ce',
        'color_accent': '#01cdfe',
        'color_card_bg': '#1e0e38',
        'color_footer_bg': '#110822',
        'body_class': 'theme-vaporwave',
        'preview_css': 'background:linear-gradient(135deg,#1a0033,#330066)',
    },
    'aurora': {
        'label': 'Nordlichter',
        'color_navbar': '#0b132b',
        'color_bg': '#0b132b',
        'color_text': '#c8e6f0',
        'color_accent': '#5ce0d8',
        'color_card_bg': '#111d3a',
        'color_footer_bg': '#080e20',
        'body_class': 'theme-aurora',
        'preview_css': 'background:linear-gradient(135deg,#0b132b,#1c2951)',
    },
    'unterwasser': {
        'label': 'Unterwasser',
        'color_navbar': '#003049',
        'color_bg': '#001828',
        'color_text': '#b0e0f0',
        'color_accent': '#00b4d8',
        'color_card_bg': '#002040',
        'color_footer_bg': '#001018',
        'body_class': 'theme-unterwasser',
        'preview_css': 'background:linear-gradient(180deg,#003049,#001828)',
    },
    'kosmos': {
        'label': 'Kosmos',
        'color_navbar': '#0a0015',
        'color_bg': '#060010',
        'color_text': '#d0c0f0',
        'color_accent': '#b088f9',
        'color_card_bg': '#0e0020',
        'color_footer_bg': '#040008',
        'body_class': 'theme-kosmos',
        'preview_css': 'background:linear-gradient(180deg,#0a0015,#060010)',
    },
    'feuer': {
        'label': 'Feuer',
        'color_navbar': '#1a0800',
        'color_bg': '#140600',
        'color_text': '#ffd6a5',
        'color_accent': '#ff6b35',
        'color_card_bg': '#1e0a00',
        'color_footer_bg': '#0a0300',
        'body_class': 'theme-feuer',
        'preview_css': 'background:linear-gradient(180deg,#1a0800,#0a0300)',
    },
}

DEFAULT_THEME: str = 'klassisch'

QUOTES_PER_PAGE: int = 20
ADMIN_QUOTES_PER_PAGE: int = 50
